### ISSUE TITLE
Decide what ```Format``` should be - only trig at present

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#28]
This:

```python
@unique
class Formats(Enum):
    """
    Enums to specify the format of nanopub desired
    """
    TRIG = 'trig'
```

and this:

```python
def fetch(uri, format: str = 'trig'):
```

are starting to look a bit embarassing, and have been hanging around in the code base for ages.

* Check which rdf formats can be returned by general nanopub servers
* Do some servers only serve a subset of these? Does ```fetch()``` need to check if a given format is available first?
* Add more RDF formats to ```Format``` enums, or find a better solution

Alternatively, don't bother with format selection - it gets parsed into an rdflib graph immediately anyway, so the format that is fetched doesn't really matter. But in such a case this code should be cleaned up.

Methods for providing the nanopub rdf serialized into a number of optional formats (trig, ttl, nt etc) would be useful, regardless.

**Comment by svenvanderburg** [comment]
I vote for getting rid of this. Indeed we parse it into an rdflib graph immediately.

**Comment by raar1** [comment]
Would it be worth having the format fetched by the library in some central config file of the library? Hardcoding is probably OK, since all nanopub servers _should_ provide trig if asked, but maybe we should have a fallback list that the library can try in the event that the server only provides turtle or nt etc?

**Comment by svenvanderburg** [comment]
Hmmm. Then we have a fallback list of servers and file formats. I see the point, but can we not just assume all servers should provide trig and keep things simple? They all run the same software. We can always implement it if we really run into problems with this.

Indeed it is good to make some constant out of it: NANOPUB_FETCH_FORMAT. I think putting it in client.py is ok (instead of a central location), because we will only use it there.

**Comment by svenvanderburg** [comment]
Ok, we'll go for NANOPUB_FETCH_FORMAT (and remove all the enum stuff)
