### ISSUE TITLE
Add some sort of ```retract()``` method

### ISSUE THREAD

**Issue by raar1** [fair-workflows/nanopub#8]
I believe you can retract nanopubs that have been published, if you have the original key it was signed with. We will want to have this capability in the client at some stage.

**Comment by svenvanderburg** [comment]
@raar1 Do you have any pointers to documentation on nanopub deletion? I couldn't find anything in the [nanopub-java paper](https://arxiv.org/pdf/1508.04977.pdf), and in the [nanopub guidelines](http://www.nanopub.org/guidelines/1.8/) I find this:
_As the primary purpose of nanopublication is to attach a reputation to a scientific assertion, it will not be possible to delete nanopublications once they have been released. Citation and impact metrics need to consider the entire legacy of one’s nanopublication record and so nanopublications must be preserved in the public record indefinitely. This includes nanopublications that may subsequently be ‘proved’ to be false or in error at a later date. Also, it is important to preserve the legacy of nanopublications in order to reveal research trends that could be exploited for knowledge discovery. With this in mind, nanopublications can be revised only to delete, add or correct information in the Provenance section (attribution, supporting). Any change in the Assertion section constitutes an entirely new nanopublication. Nanopublication revisions must contain meaningful edits, and cannot be exact duplications of existing nanopublications. Earlier versions of nanopublications can be “deprecated” by including dc:isReplacedBy <new_nanopub_uri> . By defualut, OPS will search for and cache only the most recent versions of any nanopulbication._ From which I would conclude that deletion is not possible.

**Comment by tkuhn** [comment]
Deletion is not possible, but nanopubs can be declared retracted. Example of such a retraction nanopub: http://purl.org/np/RAYskLSM5x29icArnWvo9nVrIVEN2mfPoDq3TQSgm-9kk

If the nanopub to be retracted is signed, then the retraction should be signed with the same key.

**Comment by svenvanderburg** [comment]
Thanks for the clarification @tkuhn! I guess this was all already in the mind of @raar1, as it is obvious he is proposing a `retract()` method, and not a `delete()` method... But you made me see the light: I was understanding retraction as something we had to do with the to-be-retracted nanopublication, but instead we retract it by publishing a new nanopublication retracting the to-be-retracted nanopublication.

The example is really useful!
